# Generated by Django 5.1.2 on 2024-10-16 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='klucz_obc1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='model_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liczba', models.IntegerField()),
                ('klucz_obc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.klucz_obc1')),
            ],
        ),
    ]
