# Generated by Django 5.1.2 on 2024-10-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0002_model_1_tekst'),
    ]

    operations = [
        migrations.AddField(
            model_name='klucz_obc1',
            name='klucz',
            field=models.FloatField(default=0),
        ),
    ]
